Localization automation
ansible/ansible-collection-memsource pull request #16
Opened 2022-06-21 14:49 UTC by adityamulik

- Role created for extracting strings from a project, uploading the strings to Memsource Client for translation.
- Role created for extracting translated strings from the project, pushing it back to the project repository by creating a pull request.
- Two playbooks each for it's respective pre-translation and post-translation has been created.
- Variables are defined in group vars.

2022-06-21 18:35 UTC, rooftopcellist requested changes

2022-06-21 18:35 UTC, rooftopcellist commented on roles/pre_translation/tasks/upload_strings_to_memsource.yml
> +# - name: Assertions
We should be able to un-comment this now.

2022-06-21 18:38 UTC, rooftopcellist commented
If I am understanding this correctly, this role will one work for a single project at a time.  So if a team had say, multiple repos that they wanted to push/pull strings from, they could achieve this with Controller by creating multiple job templates using the same playbook (for ex.: pre_translation.yml) for each repo, and string them together as a Workflow Job template.  Or they could achieve something similar with something like a Jenkins pipeline.

2022-06-23 18:37 UTC, adityamulik commented on roles/pre_translation/tasks/upload_strings_to_memsource.yml
> +# - name: Assertions
Uncommented, tested and will open a PR for the same.

2022-06-23 18:37 UTC, adityamulik commented on roles/pre_translation/.travis.yml
> +python: "2.7"
Updated the version to 3.8 for both roles, will merge it with opening a PR

2022-06-24 17:15 UTC, adityamulik commented on roles/pre_translation/tasks/extract_strings_from_upstream.yml
> +- name: Temporate Repository Storage Directory
Updated typos as per PR https://github.com/ansible/ansible-collection-memsource/pull/20

2022-06-24 17:15 UTC, adityamulik commented on roles/pre_translation/.travis.yml
> +python: "2.7"
Updated per PR https://github.com/ansible/ansible-collection-memsource/pull/20

2022-06-24 17:15 UTC, adityamulik commented on roles/pre_translation/meta/main.yml
> +  company: your company (optional)
Details have been filled as per https://github.com/ansible/ansible-collection-memsource/pull/20

2022-06-24 17:16 UTC, adityamulik commented on roles/pre_translation/tasks/upload_strings_to_memsource.yml
> +#       - memsource_password | default('') | length
fixed per pr https://github.com/ansible/ansible-collection-memsource/pull/20

2022-06-24 17:17 UTC, adityamulik commented
@rooftopcellist Yes, so each repository will have an individual project on Memsource for translation and similarly pull/ push roles will be applicable for each project.

2022-06-27 13:46 UTC, rooftopcellist commented
@adityamulik technically, each _component_ (awx, galaxy, pinakes) will have it's own memsource project with api and ui strings pushed to it.  

> @rooftopcellist Yes, so each repository will have an individual project on Memsource for translation and similarly pull/ push roles will be applicable for each project.

2022-06-28 18:20 UTC, adityamulik commented
This PR is good to be closed without merging

2022-06-28 18:20 UTC, closed without merging